// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaMaestro.API.Data;

#nullable disable

namespace PizzaMaestro.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260823152509_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PizzaMaestro.API.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Hydration")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("SaltPercent")
                        .HasColumnType("double");

                    b.Property<string>("YeastType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Hosszú, kontrollált fermentáció friss élesztővel.",
                            Hydration = 60.0,
                            Name = "24 órás klasszikus",
                            SaltPercent = 2.7999999999999998,
                            YeastType = "Friss élesztő"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A li.co.li. karakteresebb, aromásabb tésztához.",
                            Hydration = 62.0,
                            Name = "Folyékony kovász",
                            SaltPercent = 3.0,
                            YeastType = "Folyékony kovász"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Szilárd kovászra épülő, hosszabb fermentációhoz.",
                            Hydration = 60.0,
                            Name = "Lievito madre",
                            SaltPercent = 3.0,
                            YeastType = "Lievito madre"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
