// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaMaestro.API.Data;

#nullable disable

namespace PizzaMaestro.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PizzaMaestro.API.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BallWeight")
                        .HasColumnType("double");

                    b.Property<int>("Balls")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("FlourGrams")
                        .HasColumnType("double");

                    b.Property<double>("FridgeHours")
                        .HasColumnType("double");

                    b.Property<double>("FridgeTemp")
                        .HasColumnType("double");

                    b.Property<double>("Hydration")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("RoomHours")
                        .HasColumnType("double");

                    b.Property<double>("RoomTemp")
                        .HasColumnType("double");

                    b.Property<double>("SaltGrams")
                        .HasColumnType("double");

                    b.Property<double>("SaltPercent")
                        .HasColumnType("double");

                    b.Property<double>("SourdoughFlourGrams")
                        .HasColumnType("double");

                    b.Property<double>("SourdoughWaterGrams")
                        .HasColumnType("double");

                    b.Property<double>("TotalDoughWeight")
                        .HasColumnType("double");

                    b.Property<double>("TotalHours")
                        .HasColumnType("double");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("WaterGrams")
                        .HasColumnType("double");

                    b.Property<double>("YeastGrams")
                        .HasColumnType("double");

                    b.Property<string>("YeastLabel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("YeastType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BallWeight = 0.0,
                            Balls = 0,
                            CreatedAt = new DateTime(2026, 8, 23, 17, 6, 36, 141, DateTimeKind.Utc).AddTicks(692),
                            Description = "Hosszú, kontrollált fermentáció friss élesztővel.",
                            FlourGrams = 0.0,
                            FridgeHours = 0.0,
                            FridgeTemp = 0.0,
                            Hydration = 60.0,
                            Name = "24 órás klasszikus",
                            RoomHours = 0.0,
                            RoomTemp = 0.0,
                            SaltGrams = 0.0,
                            SaltPercent = 2.7999999999999998,
                            SourdoughFlourGrams = 0.0,
                            SourdoughWaterGrams = 0.0,
                            TotalDoughWeight = 0.0,
                            TotalHours = 0.0,
                            WaterGrams = 0.0,
                            YeastGrams = 0.0,
                            YeastLabel = "",
                            YeastType = "Friss élesztő"
                        },
                        new
                        {
                            Id = 2,
                            BallWeight = 0.0,
                            Balls = 0,
                            CreatedAt = new DateTime(2026, 8, 23, 17, 6, 36, 141, DateTimeKind.Utc).AddTicks(745),
                            Description = "A li.co.li. karakteresebb, aromásabb tésztához.",
                            FlourGrams = 0.0,
                            FridgeHours = 0.0,
                            FridgeTemp = 0.0,
                            Hydration = 62.0,
                            Name = "Folyékony kovász",
                            RoomHours = 0.0,
                            RoomTemp = 0.0,
                            SaltGrams = 0.0,
                            SaltPercent = 3.0,
                            SourdoughFlourGrams = 0.0,
                            SourdoughWaterGrams = 0.0,
                            TotalDoughWeight = 0.0,
                            TotalHours = 0.0,
                            WaterGrams = 0.0,
                            YeastGrams = 0.0,
                            YeastLabel = "",
                            YeastType = "Folyékony kovász"
                        },
                        new
                        {
                            Id = 3,
                            BallWeight = 0.0,
                            Balls = 0,
                            CreatedAt = new DateTime(2026, 8, 23, 17, 6, 36, 141, DateTimeKind.Utc).AddTicks(747),
                            Description = "Szilárd kovászra épülő, hosszabb fermentációhoz.",
                            FlourGrams = 0.0,
                            FridgeHours = 0.0,
                            FridgeTemp = 0.0,
                            Hydration = 60.0,
                            Name = "Lievito madre",
                            RoomHours = 0.0,
                            RoomTemp = 0.0,
                            SaltGrams = 0.0,
                            SaltPercent = 3.0,
                            SourdoughFlourGrams = 0.0,
                            SourdoughWaterGrams = 0.0,
                            TotalDoughWeight = 0.0,
                            TotalHours = 0.0,
                            WaterGrams = 0.0,
                            YeastGrams = 0.0,
                            YeastLabel = "",
                            YeastType = "Lievito madre"
                        });
                });

            modelBuilder.Entity("PizzaMaestro.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PizzaMaestro.API.Models.Recipe", b =>
                {
                    b.HasOne("PizzaMaestro.API.Models.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("PizzaMaestro.API.Models.User", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
